<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>customerName</name>
   <tag></tag>
   <elementGuidId>c182d20f-7bba-47d5-bf07-16f1f5d72549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[normalize-space()=&quot;${name}&quot;]/parent::tr/child::td[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
