<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobileNo</name>
   <tag></tag>
   <elementGuidId>ecd5b123-a0fe-4b6f-be81-d4856e6a5c21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[normalize-space()=&quot;${name}&quot;]/parent::tr/child::td[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
